8 add login & sign up screens
Use-By/Use-By-App pull request #23
Opened 2020-10-22 20:36 UTC by AnastasiiaMalaia

#8 Добавила экраны регистрации и входа

2020-10-23 16:13 UTC, couatl commented on UseBy/Components/Button.swift
> +        case disactive
Я вот это состояние уже поддержала вроде как, через поле isEnabled

2020-10-23 16:13 UTC, couatl commented on UseBy/Components/Button.swift
> +        case disactive
Чуть ниже есть такой код: 
```
override var isEnabled: Bool {
        didSet {
            if !isEnabled {
                backgroundColor = Colors.disabledBGColor
            }
        }
    }
```

2020-10-23 16:14 UTC, couatl commented on UseBy/Components/Button.swift
> +        case disactive
Это значит если мы у кнопки сделаем isEnabled = false, то у кнопки поменяется фон - на серый 
Кстати возможно стоит сделать еще чтобы цвет текста становился белым
И возможно если обратно сделать isEnabled=true, то цвет фона не изменится ))) 
В общем предлагаю тебе пока это убрать, потому что уже есть

2020-10-23 16:15 UTC, couatl commented on UseBy/Components/Line.swift
> +        //Keep using the method addLineToPoint until you get to the one where about to close the path
Лучше напиши тут нормальный комментарий, что здесь не работает, что нужно доделать

2020-10-23 16:15 UTC, couatl commented on UseBy/Components/Line.swift
> +//        aPath.fill()
А то выглядит как-то неаккуратно, какие-то куски кода непонятные закоменченные)

2020-10-23 16:16 UTC, couatl commented on UseBy/Components/MainTextLabel.swift
> +final class MainText: UILabel {
Я бы назвала ScreenTitle - так будет понятно что это заголовок экранов

2020-10-23 16:16 UTC, couatl commented on UseBy/Components/MainTextLabel.swift
> +    public enum TextType {
И здесь тогда ScreenType

2020-10-23 16:17 UTC, couatl commented on UseBy/Components/TextField.swift
> +//  TextField.swift
Лучше папку переназвать по названию класса внутри - AuthTextField

2020-10-23 16:18 UTC, couatl commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +// Кнопка ""Already have an account?""
У комментариев хорошо бы тоже иметь отступ как у кода

2020-10-23 16:18 UTC, couatl commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        //stackviewFields.alignment = .center
Тут опять непонятные закоменченные куски кода
Кажется нужен комментарий какой-то к ним или просто их удалить

2020-10-23 16:19 UTC, couatl commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +    //private let line = Line(frame: CGRect(x: 0, y: 0, width: 0, height: 0), lineColor: Colors.disabledColor)
И тут еще комментарий

2020-10-24 20:35 UTC, AnastasiiaMalaia commented on UseBy/Components/Button.swift
> +        case disactive
Да, не заметила 
Убрала)

2020-10-24 20:36 UTC, AnastasiiaMalaia commented on UseBy/Components/Line.swift
> +        //Keep using the method addLineToPoint until you get to the one where about to close the path
А если ничего не рисуется, т.е ничего не работает?)

2020-10-24 20:37 UTC, AnastasiiaMalaia commented on UseBy/Components/Line.swift
> +//        aPath.fill()
Можно пока удалить этот компонент, чтобы не смущал

2020-10-24 20:46 UTC, AnastasiiaMalaia commented on UseBy/Components/MainTextLabel.swift
> +final class MainText: UILabel {
Хорошо

2020-10-24 20:46 UTC, AnastasiiaMalaia commented on UseBy/Components/MainTextLabel.swift
> +    public enum TextType {
Ок

2020-10-25 09:22 UTC, couatl commented on UseBy/Components/Line.swift
> +        //Keep using the method addLineToPoint until you get to the one where about to close the path
(((( : 
// Разобраться почему не работает 
: D

2020-11-08 15:43 UTC, blackplayerten requested changes
во-1 не хватает скрытия клавиатуры по тапу куда-нибудь
 во-2 кнопка логин не кликабельна, не могу перейти на логин
в-3 при создании необходимо сделать 2 поля с паролем: ввод и подтверждение пароля
в-4 возможно стоит какие-то компоненты объединить в 1 файле? Например файл с кастомными кнопками, лейблами и тд
в-5 соблюдаем код стайл и думаем над модификаторами доступа

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +            self.isSecureTextEntry = false
по умолчанию isSecureTextEntry = false

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +            self.isSecureTextEntry = false
аналогично

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +
убрать лишнюю пустую строку

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +
аналогично

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +
аналогично

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +class AuthTextField: UITextField {
наверное не очень правильно называть именно AuthTextField, у вас только в авторизации будут кастомные тф?

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +    public enum TextFieldPurpose {
почему паблик? internal не справляется?)

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +        clearButtonMode =  UITextField.ViewMode.whileEditing
clearButtonMode =  .whileEditing

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +import SnapKit
здесь не используется снапкит, тут он не нужен)

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +//  TextField.swift
тут название стоит поменять на актуальное, а то путаница)

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/MainTextLabel.swift
> +    public enum ScreenType {
аналогично енаму в тф

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +    private let purpose: TextFieldPurpose
зачем делать свойство, которое нигде не используется? можно же сразу switch purpose

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/MainTextLabel.swift
> +    private let screenType: ScreenType
аналогично полю типа енама в тф

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/MainTextLabel.swift
> +    init(textType: ScreenType = .createAccount) {
наверное лучше назвать labelType, а не textType

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/MainTextLabel.swift
> +        switch self.screenType {
убрать self

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Components/MainTextLabel.swift
> +        self.screenType = .createAccount
не нужно будет тоже

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Localizations/ru-RU.lproj/Localizable.strings
> +"email" = "Email";
наверное как "Электронная почта"?

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +//  CreateAccViewController.swift
можно не экономить буквы) CreateAccountViewController

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +    struct CreateAccViewUIConstants {
необходимо сделать private и в названии можно убрать CreateAccView, поскольку эти константы относятся только к этому контроллеру)

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +    private let createAccountButton = MainButton(
между переменными стоит делать "логические отступы" в виде пустых строк, для наглядности

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        static let backgroundColor = Colors.mainBGColor
она нигде не используется, убрать

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        view.addSubview(createAccountButton)
можно заменить на 
```swift
[createAccountLabel, alreadySignUpButton, createAccountButton].forEach { 
     view.addSubView($0) 
}
```

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        createAccountLabel.textAlignment = .center
лучше это вынести в компонент с лейблом, тк относиться к его дезигну

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        let arrangedSubview = [textFieldName, textFieldEmail, textFieldPassword]
arrangedSubviews

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +//            make.bottom.equalTo(view).offset(CreateAccViewUIConstants.alreadySignUpButtonMargin)
убрать лишнии комментарии

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +            make.height.equalTo(MainButton.buttonHeight)
свойство это у MainButton также можно сделать internal

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        }
это можно объединить через forEach

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        guard let keyboardSize = userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue else { return }
let rectangle = info[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect else { return }
а потом kyboardSize = rectangle.size
NSValue из objective-c

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        _ = keyboardSize.cgRectValue.height
убрать, раз не используется здесь

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +    var topConstraint: Constraint?
private

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        static let backgroundColor = Colors.mainBGColor
не используется, убрать

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        static let signUpButtonPadding: CGFloat = -40
лучше делать все константы +, а там где нужно уже в процессе верстки подставлять -

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +    var composeViewBottomConstraint: Constraint?
private

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +    var composeStackOfFieldBottomConstraint: Constraint?
private

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        let arrangedSubview = [textFieldEmail, textFieldPassword]
аналогично в CreateAccount

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        }
аналогично

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        loginLabel.textAlignment = .center
тоже вынести в компонент

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        let keyboardHight = keyboardSize.cgRectValue.height
аналогично

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        UIView.animate(withDuration: 0.3) {
клавиатура появляется и исчезает по умолчанию с анимацией, тут она бесполезна

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        UIView.animate(withDuration: 0.3) {
клавиатура появляется и исчезает по умолчанию с анимацией, тут она бесполезна

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        UIView.animate(withDuration: 0.3) {
аналогично

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +    @objc func keyboardWillShow(notification: NSNotification) {
private

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +    @objc func keyboardWillHide(notification: Notification) {
private

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +            self.composeStackOfFieldBottomConstraint?.update(offset: 50)
50 вынести в константы наверху

2020-11-08 15:43 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +            self.composeAlreadyButtomConstraint?.update(offset: -(keyboardHight + 5))
20 и 5 вынести в константы наверху

2020-11-09 17:27 UTC, AnastasiiaMalaia commented on UseBy/Components/AuthTextField.swift
> +class AuthTextField: UITextField {
Есть еще вроде как у профиля, @fillinmar, у тебя есть TextField?

2020-11-09 17:40 UTC, AnastasiiaMalaia commented on UseBy/Components/MainTextLabel.swift
> +    private let screenType: ScreenType
Не поняла

2020-11-09 17:42 UTC, AnastasiiaMalaia commented on UseBy/Localizations/ru-RU.lproj/Localizable.strings
> +"email" = "Email";
Я думала, что всем привычно Email, но ладно)

2020-11-09 17:49 UTC, AnastasiiaMalaia commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        static let backgroundColor = Colors.mainBGColor
Используется в 52 строке:
view.backgroundColor = Colors.mainBGColor

2020-11-09 18:04 UTC, AnastasiiaMalaia commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +            make.height.equalTo(MainButton.buttonHeight)
А в чем разница?

2020-11-09 18:11 UTC, AnastasiiaMalaia commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        static let backgroundColor = Colors.mainBGColor
Используется

2020-11-09 18:14 UTC, AnastasiiaMalaia commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        static let signUpButtonPadding: CGFloat = -40
XCode ругается

2020-11-09 18:36 UTC, couatl commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        createAccountLabel.textAlignment = .center
По дизайну этот лейбл может быть не только по центру, поэтому не надо

2020-11-09 18:39 UTC, couatl commented on UseBy/Components/AuthTextField.swift
> +    private let purpose: TextFieldPurpose
Оно потом будет использоваться в валидации, так что убирать не надо

2020-11-09 18:40 UTC, couatl commented on UseBy/Components/AuthTextField.swift
> +class AuthTextField: UITextField {
Там не TextField, а нечто другое 
Будет еще поле для ввода имени и тега при создании 
Здесь наверное правда стоит переназвать

2020-11-09 18:51 UTC, couatl commented
>  во-2 кнопка логин не кликабельна, не могу перейти на логин
Здесь и не должно быть этой функциональности, она сделана в другой задаче

> в-3 при создании необходимо сделать 2 поля с паролем: ввод и подтверждение пароля
Делать 2 формы штука сомнительная, в facebook например такого нет 
В большинстве случаев реввод пароля не пригождается и практика скорее старая и заезженная, чем функциональная с точки зрения UI 
Тут больше пользы от возможности "забыл пароль" есть

> в-4 возможно стоит какие-то компоненты объединить в 1 файле? Например файл с кастомными кнопками, лейблами и тд
Думаю лучше оставить что один компонент - один файл, так код будет чище и по названию понятно что лежит внутри

2020-11-15 19:40 UTC, AnastasiiaMalaia commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        guard let keyboardSize = userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue else { return }
![Снимок экрана 2020-11-15 в 22 40 24](https://user-images.githubusercontent.com/58907495/99194904-96e1fa80-2793-11eb-9943-02810eec904a.png)

2020-11-15 19:58 UTC, AnastasiiaMalaia commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        view.addSubview(createAccountButton)
Не получается

2020-11-15 20:34 UTC, AnastasiiaMalaia commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        let keyboardHight = keyboardSize.cgRectValue.height
не работает

2020-11-17 14:34 UTC, couatl commented on UseBy/Screens/MainAuth/LoginViewController.swift
> +        loginLabel.textAlignment = .center
Писала выше - выносить не надо

2020-11-18 15:11 UTC, blackplayerten commented on UseBy/Screens/MainAuth/CreateAccViewController.swift
> +        guard let keyboardSize = userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue else { return }
тут info = notification.info

2020-11-21 13:58 UTC, blackplayerten approved these changes

2020-11-21 13:58 UTC, merged