Навигации между экранами авторизации
Use-By/Use-By-App pull request #25
Opened 2020-10-25 00:17 UTC by couatl

Resolves #10

2020-10-30 18:59 UTC, blackplayerten requested changes

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +    public func isEmpty() -> Bool {
у textField, и так есть isEmpty:
```swift
let textF = UITextField()
textF.text?.isEmpty
```

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Components/InputLineDivider.swift
> +    public static func getInputDividers(count: Int) -> [InputLineDivider] {
почему оно возвращает несколько полосок?
у тебя создание объектов в этом же классе
либо это снаружи делать, либо проще сделать 1 инпут, который выглядит как UIView с нижней обводкой + в нем textField

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/MainAuth/MainAuthViewController.swift
> +        navigationController?.isNavigationBarHidden = false
у тебя получается, класс MainAuthViewController, с которого осуществляется переход на другой экран, контролирует внешний вид этого экрана

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/MainAuth/MainAuthViewController.swift
> +        navigationController?.isNavigationBarHidden = false
как и выше

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Utils/Validator.swift
> +    fields.forEach { field in
если хочешь, то fields.map().filter()

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Utils/Validator.swift
> +        if let error = error {
если оставишь текущее решение, то лучше написать в 1 строчку: 
```swift
if let error = field.validate() {
```

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/AppDelegate.swift
> +    var navigationController: UINavigationController?
не имеет смысла, достаточно локальной переменной в функции

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Components/InputLineDivider.swift
> +    public static let dividerHeight = 1
зачем public?

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Utils/Validator.swift
> +    static let passwordLength = 6
сильный пароль – пароль не меньше 8 символов

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/Login/LoginViewController.swift
> +                make.height.equalTo(InputLineDivider.dividerHeight)
можно сразу создать UIView с размером
или 
внутренняя константа в классе не имеет смысла, так как длина все равно контролируется извне констрейнтами

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +        let arrangedSubview = [textFieldName,
стоит назвать arrangedSubviews, потому что это массив вьюшек и даже сам конструктор принимает arrangedSubviews

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +        navigationController?.isNavigationBarHidden = false
аналогично

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +            let alert = UIAlertController(
напоминаю: если будешь переиспользовать алерт, то вынеси его в отдельный класс с удобным интерфейсом вызова

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +    private func checkForEnablingMainActionButton() {
при стирании текста нужно обратно дизейблить кнопку, лучше делать через делегат textField

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Utils/Validator.swift
> +    return validationErrors.map { error in
так покрасивее: map { $0.text }

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +            let alert = UIAlertController(
Ошибки валидации при вводе неправильно делать на алерте, потому что:
1. если было бы 10 полей, то пользователю пришлось бы запоминать, где какие ошибки, потому что чтобы исправить ошибку, надо скрыть алерт, на котором оно показывается;
2. пользователю будет удобнее видеть ошибку под полем, где она произошла или в крайнем случае выводить все ошибки после всех инпутов.

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/Login/LoginViewController.swift
> +    private func checkForEnablingMainActionButton() {
при стирании 1 символа имя/почта/пароль могут стать не валидными, нужно обратно дизейблить кнопку, лучше это делать через делегат textField

2020-10-30 18:59 UTC, blackplayerten commented on UseBy/Screens/Login/LoginViewController.swift
> +    private func checkForEnablingMainActionButton() {
аналогично кейсу в `CreateAccViewController`

2020-11-07 13:46 UTC, couatl commented on UseBy/Utils/Validator.swift
> +    static let passwordLength = 6
У firebase требования на пароль - не меньше 6 символов

2020-11-07 19:47 UTC, couatl commented on UseBy/Screens/MainAuth/MainAuthViewController.swift
> +        navigationController?.isNavigationBarHidden = false
А как правильнее ?

2020-11-09 17:53 UTC, couatl commented on UseBy/Components/AuthTextField.swift
> +    public func isEmpty() -> Bool {
Метод isEmpty все равно оставила - иначе анвраппить опшинал везде пришлось бы
А внутренность заменила на textF.text?.isEmpty

2020-11-09 17:53 UTC, couatl commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +            let alert = UIAlertController(
У нас не будет 10 полей, поэтому кажется что валидация алертом будет оптимальнее

2020-11-09 17:55 UTC, couatl commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +    private func checkForEnablingMainActionButton() {
Поправила чтобы при стирании тоже дизейблился 
А как через делегат красиво сделать не поняла

2020-11-14 12:57 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +    public let field: UITextField = UITextField()
почему опять паблик???

2020-11-14 12:57 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +        field.borderStyle = UITextField.BorderStyle.none
UITextField.ViewMode можно убрать

2020-11-14 12:57 UTC, blackplayerten commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +            let alert = UIAlertController(
ок, это ваш ux, как пожелаете

2020-11-14 12:58 UTC, blackplayerten commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +    private func checkForEnablingMainActionButton() {
есть метод у текст филда на делегат при каждом вводе

2020-11-14 13:00 UTC, blackplayerten commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +    private func checkForEnablingMainActionButton() {
textFieldDidChange и тд

2020-11-14 13:02 UTC, couatl commented on UseBy/Components/AuthTextField.swift
> +    public let field: UITextField = UITextField()
По моему ты не писала что нужно сделать его private. Во всяком случае не в этом пулл реквесте. 
Паблик потому что затем для этих полей навешивается обработчик ввода символов
Плюс делала по аналогии с UIKit вью, в которых также есть доступ к внутренним вью (в кнопке есть доступ к лейблу внутри, в navigation контроллере есть доступ к внутенним вью)

2020-11-14 13:05 UTC, blackplayerten requested changes

2020-11-14 13:05 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +    public func validate() -> ValidationError? {
почему они все public????

2020-11-14 13:05 UTC, blackplayerten commented on UseBy/Components/InputLineDivider.swift
> +class InputLineDivider: UIView {
это же больше не используется нигде

2020-11-14 13:07 UTC, blackplayerten commented
разобраться с uitextfielddelegate

2020-11-14 13:23 UTC, couatl commented on UseBy/Components/AuthTextField.swift
> +    public func validate() -> ValidationError? {
так validate потом используется в валидаторе

2020-11-14 13:23 UTC, couatl commented on UseBy/Components/AuthTextField.swift
> +    public func validate() -> ValidationError? {
А валидатор принимает на вход TextField'ы и вызывает у них validate

2020-11-14 13:25 UTC, couatl commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +    private func checkForEnablingMainActionButton() {
А в чем преимущество через делегат делать?

2020-11-14 13:25 UTC, couatl commented on UseBy/Screens/SignUp/CreateAccViewController.swift
> +    private func checkForEnablingMainActionButton() {
Мне кажется тут нет разницы

2020-11-14 13:28 UTC, blackplayerten commented on UseBy/Components/AuthTextField.swift
> +    public let field: UITextField = UITextField()
по умолчанию все переменные создаются как internal, паблик используется как правило для библиотек
к тому же у тебя сейчас этого доступа из вне нет, так что это нужно убрать

2020-11-21 14:14 UTC, blackplayerten approved these changes

2020-11-21 14:32 UTC, merged