Создала экран профиля
Use-By/Use-By-App pull request #27
Opened 2020-10-25 22:32 UTC by fillinmar

resolves #14

2020-10-31 16:17 UTC, blackplayerten requested changes

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/AppDelegate.swift
> +        window!.rootViewController = ProfileViewController()
у вас 1 экран же не профиль

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/MainAuth/MainAuthViewController.swift
> + class MainAuthViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
ой ой ой, луше было тогда на главном экране сделать кнопку с профилем и оттуда переход на этот экран профиля, а не так все комментировать

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +        return label
наверняка у вас есть уже задизайненный ваш label, если нет, можешь сделать его, потому что такая таблица у вас много где есть

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +        }
это обычно выносят в функцию configure или как-то так
в этой строчке 
```swift 
make.right.equalTo(self).offset(-40)
``` 
константу 40 необходимо вынести в структуру в начале класса типа:
```swift
private struct UIConstants {
static let rightMarginValueLabel: CGFloat = 40
}
```
и использовать как 
```swift 
make.right.equalTo(self).offset(-UIConstants.rightMarginValueLabel)
```

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +    }
у тебя уже есть инит, этот инит можно не писать, поскольку он всегда вызывается сам в самом начале

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    private let array = ["name".localized, "email".localized, "change-password".localized, "send-feedback".localized]
название array недопустимо! непонятно, что это за массив

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    private let userArray: [String] = {
тоже некорректное название, тогда уж userDataArray

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +        super.setSelected(selected, animated: animated)
на будущее: если будет большая таблица, то стоит переопределять метод prepareForReuse, в котором будет сбрасываться состояние setSelected: isSelected = false , иначе при быстром скролле будет лаг, что не выбранные ячейки внизу будут якобы выбраны

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    private let logOutButton = MainButton(
у вас же есть линтер для форматирования? игнорировать линтер нельзя

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    var alertTitle: String = ""
как правило сначала пишут все переменные, а потом функции

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
методы, которые используются для tableViewDelegate и tableViewDataSource лучше разнести по 2 экстеншенам

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +            let alert = UIAlertController(title: alertTitle, message: nil, preferredStyle: .alert)
у алерта тайтл вроде не обязательный, можно нил кидать или сразу туда "" вставлять

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +            let alert = UIAlertController(title: alertTitle, message: nil, preferredStyle: .alert)
вынести в отдельный класс с удобным(ми) инитом(ами)

2020-10-31 16:17 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +        return [someModel.name, someModel.email, "", ""]
зачем сюда вставлять "", если значений больше нет?

2020-10-31 20:16 UTC, fillinmar commented on UseBy/Screens/Profile/ProfileViewController.swift
> +        return [someModel.name, someModel.email, "", ""]
потому что массив с названиями столбцов справа имеет 4 переменные, следовательно массив слева (с данными юзера) тоже должен иметь 4 переменные

2020-10-31 20:16 UTC, fillinmar commented on UseBy/Screens/Profile/ProfileViewController.swift
> +            let alert = UIAlertController(title: alertTitle, message: nil, preferredStyle: .alert)
а что именно вынести?)

2020-10-31 20:22 UTC, fillinmar commented on UseBy/Screens/MainAuth/MainAuthViewController.swift
> + class MainAuthViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
это вообще случайно залилось, извиняюсь х2

2020-11-14 12:00 UTC, blackplayerten requested changes

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Components/TableLabel.swift
> +    public enum TableLableTheme {
во-первых зачем паблик, во-вторых, если всего 1 кейс то зачем этот енам вообще нужен?

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileAlerts.swift
> +    init(title: String, message: String? = nil, placeholder1: String? = nil, placeholder2: String? = nil, action: AlertActions) {
по названиям непонятно что за плейсхолдеры это

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileAlerts.swift
> +class Alert {
пустая строка )

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileAlerts.swift
> +                    }
код стайл подправить

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileAlerts.swift
> +            })
code style – tab

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +    private var valueLabel = TableLable()
вообще непонятно зачем тогда этот лейбл выносить отдельно, его можно прям тут в ячейке задизайнить, он же локальный

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +    private var valueLabel = TableLable()
тем более у тебя там в ините текст иконки приложения, что совсем не вяжется с логикой таблицы, где должны быть данные пользователя🤔

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +        }*/
убирай ненужные комментарии перед ревью

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    lazy var profileTableView: UITableView = {
private

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +        }
прибивка делается снаружи, поскольку здесь только происходит установка свойств какого-то объекта

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    private let array = ["name".localized, "email".localized, "change-password".localized, "send-feedback".localized]
не исправлено

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +        tableView.register(ProfileTableViewCell.self, forCellReuseIdentifier: "My Cell")
my cell – некорректно, напрмиер ProfileSettingsCell

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +        }
switch

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +        composer.setToRecipients(["use_by@gmail.com"])
вот это нужно в lazy var, а то ты на каждый клик создаешь этот контроллер

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +            make.top.equalTo(profileTableView.snp.bottom).offset(UIConstants.tableToLogout)
какое-то странное название констнты :)

2020-11-14 12:00 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
это нужно в экстеншн с делегатом таблицы

2020-11-14 13:13 UTC, blackplayerten commented
+ у вас появился роутер, пожалуйста, вынеси презент алерта в этот роутер

2020-11-15 08:45 UTC, fillinmar commented on UseBy/Components/TableLabel.swift
> +    public enum TableLableTheme {
потому что на других экранах тоже будут таблицы, а енам нужен для создания других тем под другие таблицы

2020-11-15 08:47 UTC, fillinmar commented on UseBy/Screens/Profile/ProfileAlerts.swift
> +    init(title: String, message: String? = nil, placeholder1: String? = nil, placeholder2: String? = nil, action: AlertActions) {
с первой и второй строкой ввода текста

2020-11-15 08:52 UTC, fillinmar commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +    private var valueLabel = TableLable()
ты предлагаешь вообще убрать тэйбллейб из компонентов?

2020-11-15 08:56 UTC, fillinmar commented on UseBy/Screens/Profile/ProfileViewController.swift
> +        }
отдельной функцией?

2020-11-15 14:55 UTC, blackplayerten approved these changes

2020-11-15 15:56 UTC, merged