9 auth backend
Use-By/Use-By-App pull request #29
Opened 2020-11-28 22:26 UTC by AnastasiiaMalaia

Добавлена авторизация по логину/паролю в Firebase #9

2020-11-29 10:24 UTC, blackplayerten requested changes

2020-11-29 10:24 UTC, blackplayerten commented on UseBy/Screens/Login/LoginViewController.swift
> +    private var userAuthModel: UserAuthModel?
общение должно быть по протоколу UserAuthModelProtocol

2020-11-29 10:24 UTC, blackplayerten commented on UseBy/Screens/Login/LoginViewController.swift
> +        userAuthModel = UserAuthModel()
и тогда вынести инициализацию модели в инит вью-котроллера и прокидывать уже экземпляр извне
поскольку у вас все контроллеры инитятся через роутер, то соответственно создание экземпляра класса модели должно быть в роутере

2020-11-29 10:24 UTC, blackplayerten commented on UseBy/Screens/Login/LoginViewController.swift
> +        userAuthModel?.login(email: email, password: password, completion: ({ [weak self] error in
optional раскрыть

2020-11-29 10:24 UTC, blackplayerten commented on UseBy/Model/UserAuth.swift
> +                if (error as NSError).code == AuthErrorCode.emailAlreadyInUse.rawValue {
переделать обработку ошибок как договаривались

2020-11-29 10:24 UTC, blackplayerten commented on UseBy/Model/UserAuth.swift
> +                if (error as NSError).code == AuthErrorCode.wrongPassword.rawValue {
аналогично

2020-11-29 10:37 UTC, couatl commented on UseBy/Model/UserAuth.swift
> +    // TODO Дополнить енам ошибками
А убери TODO-шки, кажется они все выполнены

2020-11-29 10:39 UTC, couatl commented on UseBy/Screens/Login/LoginViewController.swift
> +        userAuthModel = UserAuthModel()
а разве это не странно - хранить модель в роутере? Роутер - про переходы по страницам, а там бац и в нем модели разные будут, по мне это нелогично и неочевидно

2020-11-29 10:40 UTC, couatl commented on UseBy/Screens/Login/LoginViewController.swift
> +        userAuthModel = UserAuthModel()
или может я неправильно поняла куда вынести ?

2020-11-29 19:17 UTC, blackplayerten commented on UseBy/Screens/Login/LoginViewController.swift
> +        userAuthModel = UserAuthModel()
ты просто инитишь по сути, вызываешь конструктор класса от модели

2020-12-10 14:48 UTC, AnastasiiaMalaia commented on UseBy/Model/UserAuth.swift
> +                if (error as NSError).code == AuthErrorCode.emailAlreadyInUse.rawValue {
![image](https://user-images.githubusercontent.com/58907495/101787116-cb856f80-3b0f-11eb-8abc-1ec98397338b.png)

2020-12-13 20:56 UTC, blackplayerten approved these changes

2020-12-13 20:56 UTC, merged