18 profile backend
Use-By/Use-By-App pull request #30
Opened 2020-11-30 19:06 UTC by fillinmar

валидация пароля, если пользователь зареган через гугл - в профиле три поля, имя можно изменить, НО оно не обновляется сразу, только при повторном нажатии на алерт, кнопка логаут рабочая

2020-12-02 20:16 UTC, blackplayerten requested changes

2020-12-02 20:16 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +    func fillCell(titleLabel: String, userLabel: String? = nil, googleAuth: Bool?=nil) {
разве этот бул может быть опшиналом?

2020-12-02 20:16 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileAlerts.swift
> +                }
валидацию в алерте делать не правильно, потому что алерт – просто юайный элемент, логика обработки должна быть в контроллере
соответственно и функцию проверки на валидацию, которую ты определила в классе алерта уйдет в контроллер
тебе нужно получать с алерта только данные с его текстфилдов поэтому нужно сделать так:
![image](https://user-images.githubusercontent.com/32133991/100923292-07a54880-34f0-11eb-97bb-0d8d32481f2f.png)

2020-12-02 20:16 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    private var userModel: UserModel?
через инит и роутер модель у вас будет инитится

2020-12-02 20:16 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    private var userDataArray: [String]?
этот массив не имеет уже смысла, поскольку у вас в поле класса есть пользователь, у него уже будете дергать .username, .email итд

2020-12-02 20:16 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +        }
че-то не то,
```
guard let user = userModel.get() else {
    // show alert error
    return
}
self.user = user

2020-12-02 20:16 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    }
1) этой функции не будет, поскольку можно сразу в ячейке это делать
2) userModel optional, поэтому лучше всегда раскрывать и если нил, то показывать алерт

2020-12-02 20:16 UTC, blackplayerten commented on UseBy/Screens/Profile/ProfileViewController.swift
> +                      placeholder1: "input-your-new-email-here".localized, action: .save, saveDataFromAlert: saveEmail)}
здесь после получения данных введенных с алерта, после проверки валидации уже вызываешь ваш userModel.changeEmail()

2020-12-02 20:16 UTC, blackplayerten commented on UseBy/User.swift
> +                      placeholder1: nil, placeholder2: nil, action: .none)
модель не отвечает за показ юай элементов, этим занимается вью
соответственно, нужно посылать на слой выше уведомление, произошла ли ошибка или же все ок
поэтому в методе changeEmail(newEmail: string) добавиться еще и замыкание 
```
changeEmail(newEmail: string, completion: @escaping (Error?) -> Void)
```
соответственно:
```
if let error = error {
    completion(error)
}

// а ниже, если запрос прошел успешно то 
completion(nil)  
```

и в контроллере будет выглядеть примерно так (didSelectRowAt): 
```
userModel.changeEmail(newEmail: string) { [weak self] error in
     DispatchQueue.main.async {
         if let error = error {
            // show alert
        }
        self.user.email = newEmail
     }
}

//  после обновления всех ячеек уже reloadData()
```

2020-12-02 20:22 UTC, fillinmar commented on UseBy/Screens/Profile/ProfileTableViewCell.swift
> +    func fillCell(titleLabel: String, userLabel: String? = nil, googleAuth: Bool?=nil) {
да, потому что я не всегда передаю этот бул, например, при изменении имени передавать эту переменную не имеет смысла, так как в любом случае мы можем изменить имя, также всегда можем отправить фидбэк в не зависимости от того, как пользователь авторизован

2020-12-02 20:23 UTC, fillinmar commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    private var userModel: UserModel?
да, но пока же нет роутера

2020-12-04 20:58 UTC, fillinmar commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    private var userDataArray: [String]?
этот массив нам нужен для подписей полей таблицы слева

2020-12-15 18:07 UTC, fillinmar commented on UseBy/Screens/Profile/ProfileViewController.swift
> +    }
эта функция нужна чтобы брать значение из алерта. По-другому реализовать не смогла, иначе было бы нагромождение, раз сейчас алерт - алертконтроллер.  Да, юзермодел опшионал, но если какие-то ошибки то вылезет алерт в функции setUserData

2020-12-21 08:20 UTC, blackplayerten approved these changes

2020-12-21 08:20 UTC, blackplayerten commented on UseBy/Screens/Profile/AlertController.swift
> +        self.present(alertChange, animated: true, completion: nil)
здесь не вызовется презент, убрать

2020-12-25 22:55 UTC, merged